import BootstrapClient from "@/components/BootstrapClient";
import type { Metadata } from "next";
import { Inter, Open_Sans } from "next/font/google";
import { ReduxProvicer } from "../store/reduxProvider";
// import UIProvider from "@/providers/uiProvider";
// import UIProvider from "../providers/uiProvider";

const openSans = Open_Sans({ subsets: ["latin"], display: "swap" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={openSans.className}>
        <ReduxProvicer>{children}</ReduxProvicer>
      </body>
    </html>
  );
}
